const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const root = path.join(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const source = read('src/js/analysis/skin-analysis.js');
const storefrontSource = read('src/js/catalog/storefront.js');
const html = read('index.html');
const siteCss = read('src/styles/site.css');
const hero = read('src/components/home/HeroBanner.jsx');
const brandBar = read('src/components/home/BrandBar.jsx');
const categories = read('src/components/home/CategorySection.jsx');
const productList = read('src/features/catalog/ProductCatalog.jsx');
const productCard = read('src/js/catalog/product-card.js');
const reactProductCard = read('src/features/catalog/ProductCard.jsx');
const brandShowcase = read('src/components/home/BrandShowcase.jsx');
const header = read('src/components/layout/Header.jsx');
const help = read('src/components/home/HelpSection.jsx');
const profilePage = read('src/pages/ProfilePage.jsx');
const skinAnalysisPage = read('src/pages/SkinAnalysisPage.jsx');
const homePage = read('src/pages/HomePage.jsx');
const profileCss = read('src/styles/profile.css');
const scanRefreshCss = read('src/styles/scan-refresh.css');
const profileTimeline = read('src/features/profile/components/ProfileHistoryTimeline.jsx');
const profileReport = read('src/features/profile/components/ProfileScanDetailModal.jsx');
const scanRoutine = read('src/components/analysis/SkincareRoutine.jsx');
const scanBridge = read('src/features/skin-analysis/SkinAnalysisBridge.jsx');
const scanEmail = read('src/features/skin-analysis/services/skinReportEmailService.js');
const homeCss = read('src/styles/home-refresh.css');
const homeScenesCss = read('src/styles/home-scenes.css');
const revealCss = read('src/styles/scroll-reveal.css');
const responsiveLayoutCss = read('src/styles/responsive-layout.css');
const ambientCanvasCss = read('src/styles/ambient-canvas.css');
const motionVisibility = read('src/hooks/useMotionAwareVisibility.js');
assert(!html.includes('cdn.tailwindcss.com'));
assert(siteCss.includes('@import "tailwindcss"'));
assert(siteCss.includes('--color-brand-primary'));
assert(hero.includes('className="leading-[1.05]"'));
assert(hero.includes('/images/banners/Rilastil_banner.png'));
assert(hero.includes('className="hero-carousel-controls"'));
assert(hero.includes('/images/banners/Bộ mỹ phẩm TWON giữa sắc hoa anh đào.png'));
assert(hero.includes('/images/banners/Dvah_banner.png'));
assert.equal((hero.match(/className="hero-brand-banner"/g) || []).length, 3);
assert(!hero.includes('data-feather="sparkles"'));
assert(!hero.includes('className="editorial-card editorial-card--body"'));
assert(hero.includes('className="hero-slide hero-slide--fragrance"'));
assert(hero.includes('data-carousel-dot="3"'));
assert(brandBar.includes('data-active-slide="0"'));
assert(brandBar.includes('data-active-slide="1"'));
assert(brandBar.includes('data-active-slide="2"'));
assert(brandBar.includes('data-active-slide="3"'));
assert(brandBar.includes('brand-tab-wordmark--ai">AI SKINID'));
assert(brandBar.includes(`brand-tab-wordmark--dvah">D'VAH`));
assert(siteCss.includes('.desktop-nav a.is-active'));
assert(siteCss.includes('.brand-tab.is-active::before'));
assert(storefrontSource.includes("brandTabs.forEach((tab) => tab.addEventListener('click'"));
assert(categories.includes('rilastil-acnestil-body-spray-150ml.avif'));
assert(!categories.includes("twon-body-lotion.png')} alt=\"\" /></span><span className=\"category-copy\"><small>06"));
assert(siteCss.includes('/* Balanced category grid: one premium visual system across all six cards. */'));
assert(siteCss.includes('grid-template-columns:repeat(3,minmax(0,1fr))'));
assert(productList.includes('id="brand-filter-select"'));
assert(productList.includes('id="step-filter-select"'));
assert(productList.includes('data-catalog-dropdown'));
assert(productList.includes('catalog-dropdown__panel'));
assert(productList.includes('id="benefit-filter-select"'));
assert(productList.includes('id="product-search" type="search"'));
assert(read('src/components/home/FeaturedProducts.jsx').includes('id="featured-products"'));
const featuredProducts = read('src/components/home/FeaturedProducts.jsx');
const featuredProductConfig = read('src/features/catalog/featuredProducts.js');
assert(featuredProducts.includes('FEATURED_PRODUCT_IDS'));
assert(featuredProductConfig.includes("'rilastil-1774'"));
assert(featuredProductConfig.includes("'rilastil-525'"));
assert(featuredProductConfig.includes("'rilastil-2067'"));
assert(featuredProductConfig.includes("'rilastil-1857'"));
assert(reactProductCard.includes('product-card__featured-label'));
assert(reactProductCard.includes('product-card__badge-layer'));
assert(featuredProducts.includes("useState('rilastil-1774')"));
assert(featuredProducts.includes("useState('cleanser')"));
assert(featuredProducts.includes('className={`routine-step-nav__item ${step.id === activeStep.id ? \'is-active\' : \'\'}`}'));
assert(featuredProducts.includes('routine-ellipse-stage') || featuredProducts.includes('className="routine-product-arc__item"'));
assert(featuredProducts.includes('routine-ellipse-svg') || featuredProducts.includes('className="routine-product-arc__stroke"'));
assert(featuredProducts.includes('routine-ellipse-item') || featuredProducts.includes('className="routine-product-arc__item"'));
assert(featuredProducts.includes('strokeWidth='));
assert(featuredProducts.includes('handleProductSelect') || featuredProducts.includes('activateProduct'));
assert(read('src/pages/HomePage.jsx').includes('<OfferBar revealOnUpScroll />'));
const offerBar = read('src/components/layout/OfferBar.jsx');
assert(offerBar.includes("window.addEventListener('wheel', onWheel"));
assert(offerBar.includes('isTopReadyRef.current'));
assert(!offerBar.includes('delta < -3'));
assert(featuredProducts.includes('routine-ellipse-item') || featuredProducts.includes('routine-product-layer'));
assert(featuredProducts.includes("document.dispatchEvent(new CustomEvent('skinid:open-product-detail'"));
assert(read('src/features/catalog/ProductDetailModal.jsx').includes("document.addEventListener('skinid:open-product-detail'"));
assert(header.includes('aria-controls="product-menu"'));
assert(header.includes('onMouseEnter={open}'));
assert(storefrontSource.includes("($('#featured-products') || $('#catalog'))?.scrollIntoView"));
assert(!storefrontSource.includes('setCatalogStepFilterVisibility'));
assert(!siteCss.includes('.catalog-filter-select.is-context-hidden'));
assert(siteCss.includes('/* Homepage visual rhythm and depth system. */'));
assert(siteCss.includes('--rhythm-anchor:#8b3a4a'));
assert(siteCss.includes('#categories .category-item'));
assert(siteCss.includes('.help-shop .concern-card'));
assert(siteCss.includes('.brand-card--rilastil .brand-card-media{background:radial-gradient'));
assert(siteCss.includes('.brand-card--rilastil .brand-card-media img{transform:scale(1.18)}'));
assert(siteCss.includes('.trust-strip{border-top:1px solid #eee6e8'));
assert(siteCss.includes('background:#fff;color:#302b2e'));
assert(help.includes('className="gentle-advisor-grid"') || help.includes('className="container gentle-advisor-grid"'));
assert(help.includes('openConsultation'));
assert(help.includes('tri-mun-kiem-dau'));
assert(help.includes('className="advisor-intro-title"'));
assert(help.includes('Chăm sóc da cá nhân hóa'));
assert(help.includes('Nhận gợi ý chu trình skincare ngắn gọn'));
assert(homeCss.includes('linear-gradient(110deg, #f06f8f, #df466d)'));
assert(homeScenesCss.includes('.advisor-heading-row .advisor-question'));
assert(homeScenesCss.includes('grid-template-areas: "copy media"'));
assert(homeScenesCss.includes('transform: scale(1.3) translate(5%, 0)'));
assert(homeScenesCss.includes('background: #E06D81'));
assert(homeScenesCss.includes('max-width: clamp(380px, 59svh, 510px)'));
assert(fs.existsSync(path.join(root, 'src/assets/images/banners/ai-skin-model-v1.png')));
assert(siteCss.includes('linear-gradient(135deg,#1f070c 0%,#3d121b 56%,#6b2635 100%)'));
assert(siteCss.includes('linear-gradient(135deg,#fb7185 0%,#e11d48 100%)'));
assert(siteCss.includes('background:rgba(255,255,255,.07)'));
assert(siteCss.includes('border:1px solid rgba(255,255,255,.2)!important'));
assert(siteCss.includes('backdrop-filter:blur(16px) saturate(125%)'));
assert(siteCss.includes('color:rgba(255,255,255,.78)'));
assert(storefrontSource.includes("function syncPrimaryNavigation(step = 'all')"));
assert(storefrontSource.includes("link.classList.toggle('is-active', isActive)"));
assert(source.includes('window.syncPrimaryNavigation?.(step)'));
assert(!productList.includes('placeholder="Tìm sản phẩm, hoạt chất'));
assert(!productCard.includes('public${p.image}'));
assert(!productCard.includes('<span class="product-badge ${tierColor}">${p.tier}</span>'));
assert(productCard.includes('window.SKINID_ASSET_URL'));
assert(productCard.includes(".join(' · ')"));
assert(productCard.includes('class="product-card__badge-layer"'));
assert(!productCard.includes('class="product-badges"'));
assert(productCard.includes('class="product-card__cart-button" aria-label="Thêm'));
assert(productCard.includes('<span>Mua ngay</span>'));
assert(productCard.includes('<span>Thêm vào giỏ</span>'));
assert(!productCard.includes('data-feather="zap"'));
assert(productCard.indexOf('data-cart-product-id') < productCard.indexOf('data-buy-product-id'));
assert(productCard.includes("skinid:buy-now"));
assert(reactProductCard.includes('openCheckout'));
assert(reactProductCard.includes('<ShoppingBagIcon /><span>Thêm vào giỏ</span>'));
assert(reactProductCard.indexOf('className="product-card__cart-button"') < reactProductCard.indexOf('className="product-card__buy-button"'));
assert(productCard.includes('product-card__benefit'));
assert(productCard.includes('product-card__social'));
assert(siteCss.includes('/* Flat editorial catalogue controls and product-card hierarchy. */'));
assert(siteCss.includes('border-bottom:1px solid #ebe5e7!important'));
assert(siteCss.includes('.catalog-dropdown__option.is-active'));
assert(siteCss.includes('.product-card__media img{transform:scale(1.12)}'));
assert(siteCss.includes('.product-card__footer{margin-top:auto'));
assert(brandShowcase.includes('twon-body-lotion-cutout.png'));
assert(brandShowcase.includes('dvah-kamal-cutout.png'));
assert(brandShowcase.includes('/images/brands/twon.png'));
assert(brandShowcase.includes('/images/brands/dvah.png'));
assert(!brandShowcase.includes('Xem 46 sản phẩm'));
assert.equal((brandShowcase.match(/Khám phá bộ sưu tập/g) || []).length, 3);
assert(read('src/pages/HomePage.jsx').includes('<ProductDetailModal />'));
assert(read('src/features/catalog/ProductDetailModal.jsx').includes('id="product-detail-modal"'));
assert(read('src/features/catalog/ProductDetailModal.jsx').includes('pmodal-buy-now'));
assert(read('src/features/catalog/ProductDetailModal.jsx').includes('pmodal-add-cart'));
assert(read('src/features/catalog/ProductCatalog.jsx').includes('<ResetFilterIcon />'));
assert(read('src/styles/soft-storefront.css').includes('grid-template-columns: minmax(0, 7fr) minmax(0, 3fr)'));
assert(read('src/styles/soft-storefront.css').includes('background: #fff !important;'));
assert(read('src/components/analysis/SkincareRoutine.jsx').includes('id="privacy-modal"'));
assert(!read('src/components/analysis/SkincareRoutine.jsx').includes(String.raw`</div>\n`));
assert(profilePage.includes('<OfferBar />'));
assert(profilePage.includes('<Header />'));
assert(profilePage.includes('<Footer />'));
assert(profilePage.includes('<ProfileTabs activeTab={activeTab}'));
assert(read('src/features/profile/components/ProfileTabs.jsx').includes('role="tablist"'));
assert(profilePage.includes('href="/skin-analysis"'));
assert(!profilePage.includes('Xuất Dữ Liệu (JSON)'));
assert(!profilePage.includes('downloadData'));
assert(!read('src/features/profile/services/profileService.js').includes('exportUserData'));
assert(profileCss.includes('.profile-surface'));
assert(profileCss.includes('@media (prefers-reduced-motion: reduce)'));
assert(skinAnalysisPage.includes("openAuthModal('Đăng nhập để bắt đầu soi da"));
assert(skinAnalysisPage.includes("typeof window.openPrivacyModal === 'function'"));
assert(skinAnalysisPage.includes('href="/products"'));
assert(scanRefreshCss.includes('.scan-page-body .scan-page-welcome'));
assert(scanRefreshCss.includes('@media (prefers-reduced-motion: reduce)'));
assert(scanRefreshCss.includes('.scan-result-summary__inner'));
assert(scanRoutine.includes('scan-report-action--primary'));
assert(scanRoutine.includes('Gửi qua email'));
assert(scanRoutine.includes('scan-bundle-bar'));
assert(!scanRoutine.includes('id="product-recommendations"'));
assert(scanRoutine.includes('scan-followup-mark'));
assert(scanRefreshCss.includes('.scan-metric-fill'));
assert(scanBridge.includes('latestReportRef'));
assert(!scanEmail.includes('mailto:'));
assert(!scanBridge.includes('if (event.detail.emailReport && user?.email)'));
assert(homeCss.includes('The resting state stays visible if a browser disables CSS animation.'));
assert(homePage.includes("document.body.classList.add('home-page-active')"));
assert(responsiveLayoutCss.includes('--layout-container-width'));
assert(responsiveLayoutCss.includes('.layout-container'));
assert(responsiveLayoutCss.includes('[data-layout-container]'));
assert(responsiveLayoutCss.includes('.profile-main'));
assert(responsiveLayoutCss.includes('.scan-page-body:has(#results-flow.flex) #results-flow'));
assert(read('src/main.jsx').includes("import './styles/responsive-layout.css'"));
assert(!homeCss.includes('home-page-active .container'));
assert(homePage.includes('home-refresh ambient-page-canvas scroll-reveal-root'));
assert(read('src/pages/AciePage.jsx').includes('acie-page ambient-page-canvas acie-motion-page'));
assert(ambientCanvasCss.includes('Continuous Ambient Canvas'));
assert(ambientCanvasCss.includes('.layout') === false);
assert(ambientCanvasCss.includes('@media (prefers-reduced-motion: reduce)'));
assert(homeCss.includes('/* Decorative orbits may cross the section boundary; the page canvas owns clipping. */'));
assert(homeCss.includes('right: 42px;'));
assert(homeCss.includes('pointer-events: none;'));
assert(homeCss.includes('width: 100%;\n  max-width: none;'));
assert(homeCss.includes('@media (max-width: 920px) and (min-width: 761px)'));
assert(homeCss.includes('grid-template-columns: minmax(0, .92fr) minmax(250px, .78fr) minmax(215px, .62fr)'));
assert(!homeCss.includes('.routine-step-rail { grid-column: 1 / -1'));
assert(revealCss.includes('visibility: visible !important'));
assert(motionVisibility.includes("'(prefers-reduced-motion: reduce)'"));
assert(motionVisibility.includes("typeof IntersectionObserver === 'undefined'"));
assert(profileTimeline.includes('aria-label={`Mở chi tiết phiên soi da'));
assert(profileTimeline.includes("event.key === 'Enter' || event.key === ' '"));
assert(profileReport.includes("import { createPortal } from 'react-dom'"));
assert(profileReport.includes('role="tablist" aria-label="Lọc routine theo thời điểm"'));
assert(profileReport.includes("name: 'Mức bã nhờn'"));
assert(source.indexOf('saveModernSkinReport(report') < source.indexOf("const ctxRadar = document.getElementById('radarChart')"));
assert(source.includes('window.lastSavedSkinReportSeed !== reportSeed'));
assert(source.includes('weatherData.tempC ?? weatherData.temp'));
assert(!source.includes('trước khi quá muộn'));
assert(source.includes('grid.appendChild(createProductCard(p))'));
assert(source.includes('container.appendChild(createProductCard(p))'));
assert(source.includes("variant: 'horizontal'"));
const shared = read('src/js/catalog/product-card.js');
assert(shared.includes('product-card__name'));
assert(shared.includes('product-card__selection'));
assert(shared.includes("checkbox.type = 'checkbox'"));
const checkbox = { checked: false };
const button = { disabled: true, classList: { add() {} } };
const context = {
  document: { getElementById: id => id === 'privacy-consent-checkbox' ? checkbox : button, dispatchEvent: event => event.detail.productIds.forEach(id => added.push([id, 1])) },
  window: { currentRoutineIds: ['a', 'b', 'a'], excludedRoutineIds: new Set(['b']) },
  CustomEvent: class CustomEvent { constructor(type, options) { this.type = type; this.detail = options.detail; } },
  showToast: message => messages.push(message)
};
const added = [], messages = [];
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('function togglePrivacyButton()'), source.indexOf('async function requestCameraPermissionAndProceed')), context);
context.togglePrivacyButton();
assert.equal(button.disabled, true);
checkbox.checked = true;
context.togglePrivacyButton();
assert.equal(button.disabled, false);
vm.runInContext(source.slice(source.lastIndexOf('function addAllToCart()'), source.indexOf('// BOOTSTRAP INITIALIZATION')), context);
context.addAllToCart();
assert.deepEqual(added, [['a', 1]]);
context.window.excludedRoutineIds.add('a');
context.addAllToCart();
assert.equal(added.length, 1);
assert(messages.at(-1).includes('ít nhất một'));
console.log('PASS: shared components, compiled Tailwind theme, consent states, selected routine cart items and empty selection.');
